In [1]:
import numpy as np

# 1st part. NumPy presentation

In [2]:
# Generate a matrix with size of 100 x 100 that contains random values with normal distribution with E = 0 and D = 1
A_m = np.random.normal(0, 1, (100, 100))
A_m

array([[ 1.08409828, -0.14360258,  0.18572539, ..., -1.1442376 ,
         0.56778961, -0.34335808],
       [ 0.44892247,  0.46343179,  1.64279034, ..., -1.7193891 ,
         0.38000025,  0.11814666],
       [-0.33989911, -0.0644846 ,  1.20423702, ...,  0.8053573 ,
        -0.51703304,  0.33236605],
       ...,
       [-0.28614496, -1.08255929, -1.2460041 , ..., -0.85072973,
        -1.23894014, -0.8362098 ],
       [-1.27205905,  0.4486536 ,  0.56772633, ...,  0.76837499,
        -0.90791639,  1.51612843],
       [ 0.27328752,  1.68969037, -1.08501894, ...,  0.16057064,
         0.41004502, -0.38664452]])

In [3]:
# Max value of 1st row of the matrix
np.max(A_m[0, :])

2.7576776638719642

In [4]:
# Mean value of the matrix
np.mean(A_m)

-0.0031456971123176645

In [5]:
# Standard deviation of the matrix
np.std(A_m)

1.001756398339481

In [6]:
# QR decomposition
np.linalg.qr(A_m)

(array([[-0.1093868 ,  0.00387781, -0.02807635, ...,  0.08857988,
          0.06249572,  0.01088639],
        [-0.04529681, -0.05475888, -0.16460853, ..., -0.06813447,
          0.07492227, -0.06919138],
        [ 0.03429622,  0.01058844, -0.11593291, ...,  0.1765797 ,
         -0.05195932, -0.02611363],
        ...,
        [ 0.02887236,  0.11975453,  0.12245755, ..., -0.08023809,
          0.01036543, -0.07267582],
        [ 0.12835226, -0.0347487 , -0.04376501, ..., -0.02999297,
          0.01950145,  0.10753157],
        [-0.02757503, -0.18506142,  0.10903073, ...,  0.05229676,
         -0.20820455, -0.18176744]]),
 array([[ -9.91068683,   0.98392148,   0.89715793, ...,   0.58134771,
           0.43047539,   1.29330233],
        [  0.        ,  -9.27703893,  -0.24742235, ...,   0.65031912,
          -1.16264003,   0.30191956],
        [  0.        ,   0.        , -10.14455413, ...,   0.66184311,
           0.73674687,  -1.72175743],
        ...,
        [  0.        ,   0.        ,

In [7]:
# Max value of scalar multiplication among all rows
np.max([np.dot(A_m[i, :], A_m[i, :]) for i in range(A_m.shape[0])])

139.99219328089887

In [8]:
# Standard deviation of sin(A_m)
np.std(np.sin(A_m))

0.6583536228328911

In [9]:
# Matrix multiplication
np.dot(A_m, A_m)

array([[ -6.004289  , -20.45358336,  18.44752154, ...,  -6.89585604,
        -11.85122302,   3.23083832],
       [ -4.35835401,   2.80694923,  13.82400007, ..., -19.95163046,
        -12.08388123,   6.22906666],
       [  8.59270247, -22.09326552, -27.25984088, ...,  15.20540356,
          7.91888875,  22.44939827],
       ...,
       [ 13.29723336,  -7.87735696,  -1.78920205, ..., -10.64227961,
        -15.64144097,   0.94668637],
       [  7.02260919, -16.24074142,   4.83142599, ...,  20.92500883,
         -5.96398963,  -6.07121415],
       [  4.46778856, -16.13258194,  -5.12260016, ...,  -6.77896744,
         14.07007903,  -9.40858492]])

In [10]:
# Difference of the matrix o[i] = A_m[i + 1] - A_m[i]
np.diff(A_m)

array([[-1.22770086,  0.32932797, -0.41911177, ..., -1.39969345,
         1.71202722, -0.91114769],
       [ 0.01450931,  1.17935855, -2.00926373, ...,  0.18225119,
         2.09938935, -0.26185359],
       [ 0.27541451,  1.26872162, -2.5174842 , ...,  1.01439198,
        -1.32239034,  0.84939908],
       ...,
       [-0.79641434, -0.16344481,  2.79049077, ..., -0.69648218,
        -0.38821041,  0.40273034],
       [ 1.72071265,  0.11907273,  1.09249409, ...,  0.10630898,
        -1.67629138,  2.42404482],
       [ 1.41640285, -2.77470931,  1.71605655, ...,  0.7630115 ,
         0.24947438, -0.79668954]])

In [11]:
# Fourier transformation of the matrix
np.fft.fft(A_m)

array([[ 3.26657252e+00+0.00000000e+00j, -5.49041824e-01-1.39672388e+01j,
        -7.18006866e+00+1.62876978e+01j, ...,
        -6.47851037e+00-4.96992691e-01j, -7.18006866e+00-1.62876978e+01j,
        -5.49041824e-01+1.39672388e+01j],
       [ 8.01400746e+00+0.00000000e+00j, -4.71271292e+00+1.54498648e+00j,
        -1.80760349e+00-2.10219361e+00j, ...,
        -5.11489431e+00+1.52203084e+00j, -1.80760349e+00+2.10219361e+00j,
        -4.71271292e+00-1.54498648e+00j],
       [ 1.20453575e+01+0.00000000e+00j, -1.26464029e+01-1.16114076e+01j,
         1.22460606e+01-1.82954287e+00j, ...,
        -5.04253541e+00-3.33199525e+00j,  1.22460606e+01+1.82954287e+00j,
        -1.26464029e+01+1.16114076e+01j],
       ...,
       [-1.14307170e+00+0.00000000e+00j, -2.30745144e+01+1.99142585e+00j,
         9.74089219e-01-7.41483651e-01j, ...,
        -6.37250818e+00+1.60913896e+00j,  9.74089219e-01+7.41483651e-01j,
        -2.30745144e+01-1.99142585e+00j],
       [-2.24081079e+01+0.00000000e+00j, -3.

In [12]:
# A vector from 0 to 10 that contains 10 elements
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
# A matrix with size of 10 x 10 that contains 0s
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# 2nd part. Olap cube

In [18]:
shops = 100
goods = 20
days = 30

In [19]:
def fill_cube(E_s, D_s, shops, goods, days):
    assert len(E_s) == goods
    assert len(D_s) == goods
    cube = np.zeros((shops, goods, days))
    for good in range(goods):
        cube[:, good, :] = np.random.normal(E_s[good], D_s[good], (shops, days))
    return cube

In [21]:
E_s = np.random.randint(2, 10000, goods)
D_s = [np.random.randint(1, E_s[i] / 100) for i in range(goods)]

In [22]:
cube = fill_cube(E_s, D_s, shops, goods, days)

## Looking for a day which max amount of good 1 was sold on

In [23]:
amount = 0
maxDay = 0
for i in range(cube.shape[2]):
    if amount < np.max(cube[:, 1, i]):
        amount = np.max(cube[:, 1, i])
        maxDay = i
print('The day for good 1 is {}. Amount is {}'.format(maxDay, amount))

The day for good 1 is 10. Amount is 8938.318718029706


## Looking for max amount of money

In [25]:
print("Money amount = {}".format(np.max(cube)))

Money amount = 9695.38389910845


## Looking for correlation between stores 1, 2 for good 1

In [40]:
R = np.mean((cube[1, 1, :] - np.mean(cube[1, 1, :])) * (cube[2, 1, :] - np.mean(cube[2, 1, :]))) / np.std(cube[1, 1, :]) / np.std(cube[2, 1, :])
print('Correlation is {}' .format(R))

Correlation is 0.0775313280797058


## Looking for amount of money from 1 day to 10 for 1 shop for 1 - 5 goods

In [86]:
print('Amount of money = {}'.format(np.sum(cube[1, 1:6, 1:11])))

Amount of money = 232444.71042117276
