In [1]:
import numpy as np

# 1st part. NumPy presentation

In [2]:
# Generate a matrix with size of 100 x 100 that contains random values with normal distribution with E = 0 and D = 1
A_m = np.random.normal(0, 1, (100, 100))
A_m

array([[ 0.5950902 ,  0.18355068, -0.39678919, ..., -0.23987784,
        -0.6274694 ,  0.44367194],
       [-0.70417572,  0.56355224,  1.84967355, ...,  1.57286058,
        -0.54695936, -0.68672675],
       [ 0.28228686,  1.35629418, -0.83089523, ...,  0.8662543 ,
         0.07521813,  1.04049543],
       ...,
       [ 0.08913017, -0.50818168, -1.31995869, ..., -1.02955248,
         2.12404845,  0.35018385],
       [ 0.00486937,  0.67880932,  0.79445995, ...,  1.68696934,
         1.42269372,  2.50965916],
       [ 0.44773045, -1.32727279,  1.61977179, ..., -1.03992405,
         0.17367625,  0.37197134]])

In [3]:
# Max value of 1st row of the matrix
np.max(A_m[0, :])

2.232986353800622

In [4]:
# Mean value of the matrix
np.mean(A_m)

-0.0006723063702698073

In [5]:
# Standard deviation of the matrix
np.std(A_m)

1.0136826153549672

In [6]:
# QR decomposition
np.linalg.qr(A_m)

(array([[-0.06074381, -0.01492528, -0.04448067, ..., -0.21209716,
         -0.09218642, -0.09942246],
        [ 0.07187871, -0.06162538,  0.17945658, ...,  0.13222739,
          0.01284543,  0.09776538],
        [-0.02881442, -0.1359722 , -0.10320938, ..., -0.05766195,
          0.06746789, -0.07191818],
        ...,
        [-0.00909796,  0.05216319, -0.12499732, ..., -0.0957122 ,
         -0.04550715, -0.01934762],
        [-0.00049704, -0.06890399,  0.06974583, ...,  0.05870634,
          0.02305431, -0.08003518],
        [-0.04570207,  0.1375819 ,  0.17881988, ..., -0.05985102,
         -0.17363517, -0.06303195]]),
 array([[-9.79672228, -0.60218097, -0.4574241 , ..., -0.37569033,
         -0.93381139, -0.13103815],
        [ 0.        , -9.84717993, -1.39207348, ..., -2.00341152,
          0.44280401,  0.2862209 ],
        [ 0.        ,  0.        , 10.01225759, ..., -0.42759107,
          0.31454154,  0.64540441],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  

In [7]:
# Max value of scalar multiplication among all rows
np.max([np.dot(A_m[i, :], A_m[i, :]) for i in range(A_m.shape[0])])

145.14833150504796

In [8]:
# Standard deviation of sin(A_m)
np.std(np.sin(A_m))

0.6589449039322197

In [9]:
# Matrix multiplication
np.dot(A_m, A_m)

array([[  6.48096114,   4.22687362,   1.12598669, ..., -10.04535601,
         -2.2825191 ,   2.69786555],
       [-10.36625829, -12.39953262, -15.84618171, ..., -10.73898182,
          8.713156  ,   0.81852112],
       [ 12.02676036, -15.59248703,   1.6466629 , ...,   2.6555135 ,
         -8.55618587,   9.98927295],
       ...,
       [ 11.35203872, -18.76325939,   5.03652858, ...,  13.57592739,
          7.39394941,  -7.75113813],
       [ -0.07649022,   3.85124842,  23.5529734 , ...,  12.61516014,
         -6.9219257 ,  23.22787481],
       [  4.10790626,  -6.96706866,  -3.67160828, ...,  17.18141509,
        -10.24571976,  -0.72226221]])

In [10]:
# Difference of the matrix o[i] = A_m[i + 1] - A_m[i]
np.diff(A_m)

array([[-0.41153952, -0.58033987,  0.85639404, ..., -1.85508927,
        -0.38759156,  1.07114134],
       [ 1.26772796,  1.28612131, -1.23483883, ...,  1.35390531,
        -2.11981995, -0.13976739],
       [ 1.07400731, -2.18718941, -1.12189983, ...,  3.39984995,
        -0.79103617,  0.9652773 ],
       ...,
       [-0.59731185, -0.811777  ,  2.0482502 , ...,  0.2474436 ,
         3.15360092, -1.7738646 ],
       [ 0.67393995,  0.11565063, -0.30400301, ...,  0.68031248,
        -0.26427562,  1.08696544],
       [-1.77500324,  2.94704458, -2.54221901, ..., -2.18897946,
         1.2136003 ,  0.19829509]])

In [11]:
# Fourier transformation of the matrix
np.fft.fft(A_m)

array([[ 1.64567727 +0.j        ,  9.32873081+14.01983844j,
        -6.00174263 -0.69320772j, ..., -0.99746568 +4.87114731j,
        -6.00174263 +0.69320772j,  9.32873081-14.01983844j],
       [-3.49388876 +0.j        , 11.15790679 +1.57660316j,
        -0.07418769 -2.37372474j, ...,  4.18276215 -2.47748723j,
        -0.07418769 +2.37372474j, 11.15790679 -1.57660316j],
       [ 3.76231078 +0.j        , -0.10221154 +8.79794199j,
        -4.20088685-13.89462014j, ..., -5.36378227-10.56035917j,
        -4.20088685+13.89462014j, -0.10221154 -8.79794199j],
       ...,
       [ 6.40543039 +0.j        ,  1.18541709 +0.18070095j,
        11.89864855 -2.1384233j , ..., -9.56685056 +1.77639104j,
        11.89864855 +2.1384233j ,  1.18541709 -0.18070095j],
       [15.99473895 +0.j        , 21.741305   +2.07776964j,
         6.59390791+11.58988058j, ..., -4.73155079 +7.01061801j,
         6.59390791-11.58988058j, 21.741305   -2.07776964j],
       [-8.87021817 +0.j        , -0.75944571+10.84692123j

In [12]:
# A vector from 0 to 10 that contains 10 elements
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
# A matrix with size of 10 x 10 that contains 0s
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# 2nd part. Olap cube

In [14]:
shops = 100
goods = 20
days = 30

In [15]:
def fill_cube(E_s, D_s, shops, goods, days):
    assert len(E_s) == goods
    assert len(D_s) == goods
    cube = np.zeros((shops, goods, days))
    for good in range(goods):
        cube[:, good, :] = np.random.normal(E_s[good], D_s[good], (shops, days))
    return cube

In [16]:
E_s = np.random.randint(2, 10000, goods)
D_s = [np.random.randint(1, E_s[i] / 100) for i in range(goods)]

In [17]:
cube = fill_cube(E_s, D_s, shops, goods, days)

## Looking for a day on which max count of product 1 was sold

In [18]:
amount = 0
maxDay = 0
for i in range(cube.shape[2]):
    if amount < np.max(cube[:, 1, i]):
        amount = np.max(cube[:, 1, i])
        maxDay = i
print('The day for good 1 is {}. Amount is {}'.format(maxDay, amount))

The day for good 1 is 28. Amount is 4492.049819557065


## Looking for max amount of money

In [19]:
print("Money amount = {}".format(np.max(cube)))

Money amount = 9745.36505819607


## Looking for correlation between stores 1, 2 for product 1

In [20]:
R = np.mean((cube[1, 1, :] - np.mean(cube[1, 1, :])) * (cube[2, 1, :] - np.mean(cube[2, 1, :]))) / np.std(cube[1, 1, :]) / np.std(cube[2, 1, :])
print('Correlation is {}' .format(R))

Correlation is -0.36903561265194285


## Looking for amount of money from 1 day to 10 for 1 shop for 1 - 5 products

In [21]:
print('Amount of money = {}'.format(np.sum(cube[1, 1:6, 1:11])))

Amount of money = 178819.1607046988
